Sign in server and client handler
kovtunovprog/python_async_chat pull request #13
Opened 2022-10-27 09:21 UTC by dpirohov

- Add sign in handler on server
- Add server sessions attribute
- Add sessions table in db
- Add sign in method to client
- Add token generator with 'secrets' lib
- Add "encode_content_from_json" method to Message class for encoding json contetns

2022-10-29 16:58 UTC, ArturYastrebov reviewed
nice job!

2022-10-29 16:58 UTC, ArturYastrebov commented on server/config.py
> +DATABASE_URL = "sqlite+aiosqlite:///C:/Users/k3nz0/PycharmProjects/python_async_chat/server/server_utils/database.db"
Підправ посилання на ДБ

2022-10-29 16:58 UTC, ArturYastrebov commented on server/routes/sign_in.py
> +        user = result.first()
17 та 18 рядок можна замінити на
       user = await session.scalar(select(User).where(User.nickname == content["nickname"]))

2022-10-30 09:33 UTC, dpirohov commented on server/routes/sign_in.py
> +        user = result.first()
done

2022-10-30 09:50 UTC, dpirohov commented on server/config.py
> +DATABASE_URL = "sqlite+aiosqlite:///C:/Users/k3nz0/PycharmProjects/python_async_chat/server/server_utils/database.db"
Я вернул тот что ставил ты, но у меня дб эту не видит и не создает, почему то работает только по прямому пути

2022-10-30 10:57 UTC, dpirohov commented on client/client.py
> +        self.send_message(message)
done

2022-10-30 10:58 UTC, dpirohov commented on server/models/session.py
> +from sqlalchemy import String
done

2022-10-30 11:58 UTC, dpirohov commented on server/server_utils/db_utils.py
> +from server.models.session import UserSession  # noqa
нет
Каждый раз как мы наследуем Base в метадату попадает таблица, сейчас первым импортит Base класс User, а из юзера его импортит в себя UserSessions, поэтому если не заимпортить их сейчас, таблица для создания не попадет в метадату.

2022-10-31 16:28 UTC, ArturYastrebov approved these changes

2022-11-02 12:32 UTC, Alaru-dev commented on server/server_utils/db_utils.py
> +from server.models.session import UserSession  # noqa
Все створюється без цього імпорту, видали, щоб потім десь не отримати ціклічний

2022-11-02 17:22 UTC, kovtunovprog requested changes

2022-11-02 17:22 UTC, kovtunovprog commented on server/routes/sign_in.py
> +async def create_session(user: User, connection: Connection) -> str:
Краще робити за один конекшн

2022-11-04 15:15 UTC, ArturYastrebov approved these changes
Nice job!

2022-11-04 17:04 UTC, KateSamus commented on client/client.py
> +        message = Message("sign_in", "_", "server", "_", Message.decode_content_to_json(data))
Наче вказуємо sender як client

2022-11-04 21:15 UTC, KateSamus commented on utils/protocol/message.py
> +    @classmethod
А чому decode це класметод, а encode ні?

2022-11-05 09:53 UTC, dpirohov commented on client/client.py
> +        message = Message("sign_in", "_", "server", "_", Message.decode_content_to_json(data))
поправил

2022-11-05 09:54 UTC, dpirohov commented on utils/protocol/message.py
> +    @classmethod
Encode мы используем когда обьект класса создан, а Decode когда обьекта еще нет, получается мы метод можем только с класса вызвать.  Если видишь как переписать подскажи

2022-11-05 14:59 UTC, Alaru-dev approved these changes

2022-11-05 15:06 UTC, kovtunovprog approved these changes

2022-11-05 15:31 UTC, merged