Sign up handler
kovtunovprog/python_async_chat pull request #14
Opened 2022-10-28 15:07 UTC by KateSamus

Add sign_up method to client and server handler

2022-10-29 16:21 UTC, ArturYastrebov commented on server/routes/sign_up.py
> +        session.commit()
можна обійтися без session.commit()
session.begin() при успішному додаванні виконує  session.commit() в іншому випадку робить session.rollback()

2022-10-29 16:22 UTC, ArturYastrebov commented on server/routes/sign_up.py
> -    print("SIGN UP METHOD")
Думаю прінт є лишнім. Для цього є логер.

2022-10-30 10:07 UTC, dpirohov commented on server/routes/sign_up.py
> +    content = json.loads(request.content)
Я добавили этот метод во внутрь самого месседж, если шеф одобрит можно будет из него использовать, если не одобрит я свое перепишу :)

2022-10-30 10:07 UTC, dpirohov commented on server/routes/sign_up.py
> +    async with async_session() as session:
Мы рано открываем сессию с ДБ, может сначала стоит выполнить проверку и если все ок только тогда делать конект к ДБ и уже работать в ней

2022-10-30 10:16 UTC, dpirohov commented on server/routes/sign_up.py
> +        if is_password_correct(content["password"]) is not True:
Я бы is_nickname_correct и is_password_correct вынес бы в отдельную функцию, по типу check_credentials или check_user_login_password

2022-10-30 10:19 UTC, dpirohov commented on server/routes/sign_up.py
> +    async with async_session() as session, session.begin():
Мы за один метод открываем две разных сессии в ДБ, можно сделать запрос и добавить юзера в один коннект, мы же много действий не делаем после первого ответа ДБ, по сути если ответ ДБ что такого логина нет, мы можем создать обьект  юзера и сразу сделать .add и на этом наш конект к дб закрыть, все за один подход.

2022-10-30 10:19 UTC, dpirohov commented on server/routes/sign_up.py
> +        email=content["email"],
Давай везде пользоваться get, сервер крашиться если такой ключ не прийдет

2022-10-30 10:26 UTC, dpirohov commented on server/routes/sign_up.py
> +        await add_user_to_db(content, connection)
Я бы его перенес в основной метод что бы все сделать за одно подключение, а хендлеру оставил бы только функцию ответа

2022-10-30 10:27 UTC, dpirohov commented on server/routes/sign_up.py
> +        await add_user_to_db(content, connection)
![image](https://user-images.githubusercontent.com/94925700/198873896-607b6e74-1066-4058-9e5d-cb241f6e7b37.png)

2022-10-30 10:28 UTC, dpirohov commented on server/routes/sign_up.py
> +        await add_user_to_db(content, connection)
как то так

2022-10-31 10:28 UTC, KateSamus commented on server/routes/sign_up.py
> +        session.commit()
done

2022-10-31 10:28 UTC, KateSamus commented on server/routes/sign_up.py
> -    print("SIGN UP METHOD")
цього коду вже давно нема хд

2022-10-31 10:28 UTC, KateSamus commented on server/routes/sign_up.py
> +    content = json.loads(request.content)
okay, чекатиму)

2022-10-31 10:29 UTC, KateSamus commented on server/routes/sign_up.py
> +    async with async_session() as session:
згодна, перетягнула вниз

2022-10-31 10:30 UTC, KateSamus commented on server/routes/sign_up.py
> +        if is_password_correct(content["password"]) is not True:
Гарна ідея, теж про це думала
done

2022-10-31 10:31 UTC, KateSamus commented on server/routes/sign_up.py
> +        email=content["email"],
На мою думку, десктопт має перевіряти яи заповнені обов'язкові поля

2022-10-31 15:09 UTC, KateSamus commented on server/routes/sign_up.py
> +        email=content["email"],
Поняв-прийняв, додала get)

2022-11-03 15:26 UTC, dpirohov requested changes
Переписать на одну сессию с ДБ

2022-11-03 18:38 UTC, KateSamus commented on server/routes/sign_up.py
> +        is_nickname_in_db = await session.scalar(
done

2022-11-03 18:39 UTC, KateSamus commented
> Переписать на одну сессию с ДБ

done

2022-11-03 20:36 UTC, dpirohov commented on client/client.py
> +        request = Message("sign_up", "client", "server", "_", json.dumps(data))
json.dumps(data)) - > Message.decode_content_to_json(data)
мы ж договорились туда добавить метод, я добавил

2022-11-03 20:40 UTC, dpirohov commented on server/routes/sign_up.py
> +    content = json.loads(request.content)
Тут тоже через месседж надо, договорились же юзать)

2022-11-04 10:01 UTC, KateSamus commented on client/client.py
> +        request = Message("sign_up", "client", "server", "_", json.dumps(data))
Я до того код написала, в сьогоднішніх комітах поміняла на encode i decode

2022-11-04 14:10 UTC, dpirohov approved these changes
++

2022-11-04 21:27 UTC, kovtunovprog commented on client/client.py
> +        message = Message("sign_up", "client", "server", "_", Message.decode_content_to_json(data))
Можливо варто в протокол додати ось таку штуку?

`class Commands(enum.Enum):
     sign_up = enum.auto()`
     
  Це щоб не хардкодити значення кожен раз)

2022-11-04 21:27 UTC, kovtunovprog commented on client/client.py
> +        message = Message("sign_up", "client", "server", "_", Message.decode_content_to_json(data))
Енами дуже корисна штука
https://docs.python.org/3/library/enum.html

2022-11-04 21:27 UTC, kovtunovprog commented on client/client.py
> +        message = Message("sign_up", "client", "server", "_", Message.decode_content_to_json(data))
Так само можливо варто створити єнам для client та server

Типу SenderReceiver: ...

2022-11-04 21:27 UTC, kovtunovprog commented on server/routes/sign_up.py
> +async def add_user_to_db(content: dict, session, connection: Connection):
а чи є якийсь сенс в тому що ця функция асінк? Жодного авейта немає

2022-11-04 21:27 UTC, kovtunovprog commented on server/routes/sign_up.py
> +    logger.info(
Логування це супер)

2022-11-04 21:27 UTC, kovtunovprog commented on server/routes/sign_up.py
> +    if response_text == "REGISTRATION IS SUCCESSFUL":
Таку штуку теж краще в єнам
Типу RegistrationStatuses

2022-11-04 21:27 UTC, kovtunovprog commented on server/routes/sign_up.py
> +            "NICKNAME CANNOT START WITH A SPACE AND MUST CONTAINS ONLY 4 TO 16 CHARACTERS OF THE ENGLISH ALPHABET",
Коммент про єнам для статусів реєстрації стосується всіх цих повідомлень)

2022-11-05 10:12 UTC, ArturYastrebov approved these changes

2022-11-05 14:47 UTC, merged