Add def create_chat
kovtunovprog/python_async_chat pull request #15
Opened 2022-10-28 22:54 UTC by ArturYastrebov

Add table chatmember and chat to DB
Add def create_chat

2022-10-30 10:08 UTC, KateSamus reviewed
Зробила рев'ю, передивись код, маю кілька коментарів)

2022-10-30 10:08 UTC, KateSamus commented on server/routes/create_chat.py
> +        response = Message("create_chat", "server", message.sender, "_", '{"response": "chat was created"}')
Токен генерується, коли юзер логіниться. Коли Діма замержить свій код, треба буде не забути додати токен.
Оскільки пустий токен може приходити тільки під час реєстрації чи логіну, пропоную тичасвого замінити "_" на "token", щоб не порушувати логіку коду

2022-10-30 10:08 UTC, KateSamus commented on server/routes/create_chat.py
> +        return await connection.send_message(response)
Блеком і флейком проходився? В кінці файлу нема пустої строки, мав посваритися на це х)

2022-10-31 16:13 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +from utils.protocol.connection import Connection
+ Підправив порядок імпорту

2022-10-31 16:13 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +    print("create_chat METHOD")
++

2022-10-31 16:15 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +        user = await session.scalar(select(Chat).where(Chat.chat_name == content["chat_name"]))
++

2022-10-31 16:17 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +        response = Message("create_chat", "server", message.sender, "_", '{"response": "DB has the same chat name"}')
++

2022-10-31 16:18 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +        response = Message("create_chat", "server", message.sender, "_", '{"response": "chat was created"}')
Думаю сервак відправляє юзеру токен тільки після реєстрації один раз. Далі юзеру більше не треба від сервака токен в response.

2022-10-31 16:19 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +        return await connection.send_message(response)
Пройшовся =*

2022-10-31 17:33 UTC, KateSamus submitted a review, later dismissed

2022-11-03 15:26 UTC, dpirohov commented on client/client.py
> +from utils.protocol.message import Message
тут через инит

2022-11-03 15:29 UTC, dpirohov commented on client/client.py
> +        message = Message("create_chat", "client", "server", "_", json.dumps(data))
В контенті обов'язково буде {"nickname": _, "user_id": _}

2022-11-03 15:29 UTC, dpirohov commented on client/client.py
> +        message = Message("create_chat", "client", "server", "_", json.dumps(data))
json.dumps(data)) -> в классі Месседж буде

2022-11-03 15:30 UTC, dpirohov commented on server/models/chat.py
> +    creator_id = Column(Integer)
це буде Foreignkey

2022-11-03 15:34 UTC, dpirohov commented on server/routes/create_chat.py
> +            user = await session.scalar(select(User).where(User.nickname == content["nickname"]))
user id та nickname буде приходити в content

2022-11-03 15:36 UTC, dpirohov commented on server/routes/create_chat.py
> +            chat_member = ChatMember(user_id=user.id, chat_id=chat.id, permissions=1)
Треба глянути в гайді, повинен бути метод який при створенні об'єкту поверне його ІД одразу

2022-11-03 15:38 UTC, dpirohov commented on server/routes/create_chat.py
> +        response = Message("create_chat", "server", message.sender, "_", '{"response": "Сhat was created"}')
Додати до респонс chat_id ta chat_name

2022-11-03 15:39 UTC, dpirohov requested changes
Переписати код під один коннект до ДБ

2022-11-04 12:39 UTC, ArturYastrebov commented on server/models/chat.py
> +    creator_id = Column(Integer)
++

2022-11-04 12:39 UTC, ArturYastrebov commented on client/client.py
> +from utils.protocol.message import Message
++

2022-11-04 13:21 UTC, ArturYastrebov commented on client/client.py
> +        message = Message("create_chat", "client", "server", "_", json.dumps(data))
++

2022-11-04 14:33 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +        response = Message("create_chat", "server", message.sender, "_", '{"response": "Сhat was created"}')
++

2022-11-04 16:48 UTC, KateSamus commented on client/client.py
> +        message = Message("create_chat", "client", "server", "_", json.dumps(data))
Діма додав функцію decode_from_json_format, можна замість json.dumps використовувати

2022-11-04 16:52 UTC, KateSamus commented on server/routes/create_chat.py
> +            "create_chat", "server", "_", "_", Message.decode_content_to_json({"response": "Chat name is not unique"})
В sender має client стояти, ні?

2022-11-04 17:14 UTC, KateSamus commented on server/routes/create_chat.py
> +            "create_chat", "server", "_", "_", Message.decode_content_to_json({"response": "Chat name is not unique"})
Якщо ми вже переважно капсом response пишемо, то краще так переписати
Чи як в групі вирішимо хд

2022-11-04 19:25 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +            "create_chat", "server", "_", "_", Message.decode_content_to_json({"response": "Chat name is not unique"})
++ Додав слієнт в респонс

2022-11-04 19:26 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +            "create_chat", "server", "_", "_", Message.decode_content_to_json({"response": "Chat name is not unique"})
++ Зробив капсом

2022-11-05 15:03 UTC, KateSamus approved these changes

2022-11-05 16:07 UTC, dpirohov commented on server/routes/create_chat.py
> +    if chat is not None:
Сдвинь код вправо, что б все под одним with было

2022-11-05 16:07 UTC, dpirohov commented on client/client.py
> +        message = Message("create_chat", "client", "server", "_", Message.decode_content_to_json(data))
забув токен

2022-11-05 16:14 UTC, dpirohov commented on client/client.py
> +    async def create_chat(self, data: dict):
data["user_id"] = self.user_id (спросить у ромы как будет называться переменная)

2022-11-05 16:19 UTC, dpirohov commented on server/routes/create_chat.py
> +        chat = await session.scalar(select(Chat).where(Chat.chat_name == chat_name))
https://stackoverflow.com/questions/1316952/sqlalchemy-flush-and-get-inserted-id

2022-11-05 16:19 UTC, dpirohov commented on server/routes/create_chat.py
> +        chat = await session.scalar(select(Chat).where(Chat.chat_name == chat_name))
try await session.flush()

2022-11-05 17:50 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +    if chat is not None:
++

2022-11-05 19:36 UTC, ArturYastrebov commented on client/client.py
> +        message = Message("create_chat", "client", "server", "_", Message.decode_content_to_json(data))
++

2022-11-05 19:37 UTC, ArturYastrebov commented on client/client.py
> +    async def create_chat(self, data: dict):
++

2022-11-05 19:37 UTC, ArturYastrebov commented on server/routes/create_chat.py
> +        chat = await session.scalar(select(Chat).where(Chat.chat_name == chat_name))
++

2022-11-06 15:26 UTC, dpirohov commented on server/routes/create_chat.py
> +    print(chat_name, user_id, chat_type)
удали

2022-11-06 15:27 UTC, dpirohov commented on server/routes/create_chat.py
> +                    {"response": "CHAT WAS CREATED", "chat_id": f"{chat.id}", "chat_name": f"{chat_name}"}
{"response": "CHAT WAS CREATED", "chat_id": chat.id, "chat_name": chat_name}
тут ф строка не нужна

2022-11-06 15:58 UTC, dpirohov approved these changes
++

2022-11-06 16:51 UTC, merged