Implemented base server structure, and methods
kovtunovprog/python_async_chat pull request #2
Opened 2022-10-16 17:15 UTC by dpirohov

- base server template and structure
- request protocol client - server - client and Request data class
- Connection data class
- base handlers and command(handler)map builder

2022-10-16 19:16 UTC, kovtunovprog requested changes

2022-10-16 19:16 UTC, kovtunovprog commented on utils/protocol/server.py
> +        print(request)  # TODO: log this or delete after testing
думаю лучше удалить

2022-10-16 19:16 UTC, kovtunovprog commented on utils/protocol/server.py
> +    def decode_protocol(self, data: str) -> Request:
parse_protocol_message(self, message: str) -> Message

Также думаю что это полезно и для клиента и еще для чего-то, то есть можно перенести в файл, где создается сообщение

2022-10-16 19:16 UTC, kovtunovprog commented on utils/protocol/timestamp.py
> +def form_timestamp():
а что это и зачем это здесь в протоколе?

2022-10-16 19:16 UTC, kovtunovprog commented on utils/protocol/request.py
> +class Request:
Я думаю лучше переименовать в Message (раз этот объект отвечает и за реквест и за респонс)

2022-10-16 19:16 UTC, kovtunovprog commented on utils/protocol/request.py
> +    def form_protocol(self):
from предполагает что ты создаешь этот объект из протокола (можно кстати так сделать через классметод)

а это скорее to_protocol

2022-10-16 19:16 UTC, kovtunovprog commented on utils/protocol/connection.py
> +    def send(self, message: Request):
send_message

2022-10-16 19:16 UTC, kovtunovprog commented on utils/protocol/connection.py
> +    token: str
токен это логика конкретно нашего сервера с чатиком, это не имеет отношения к конкшену как таковому, поэтому предлагаю удалить

2022-10-16 19:16 UTC, kovtunovprog commented on utils/protocol/connection.py
> +    token: str
на клиенте данные авторизации можно хранить отдельно

2022-10-16 19:16 UTC, kovtunovprog commented on server/routes/__init__.py
> +from server.routes import sign_in, sign_up, send_private_message, send_message_to_all
весь контент из роутс я думаю надо удалить на данный момент, в задачу реализация этих функций не входила

2022-10-16 19:16 UTC, kovtunovprog commented on server/routes/__init__.py
> +from server.routes import sign_in, sign_up, send_private_message, send_message_to_all
Я думаю что локально это можно оставить для тестов роме и тебе, но в репозитории это нам сейчас не нужно

2022-10-16 19:16 UTC, kovtunovprog commented on server/main.py
> +    print(server.command_map)  # TODO: delete after testing, shows that command map is working
такие вещи нужно убирать перед комитом

2022-10-16 19:16 UTC, kovtunovprog commented on server/config/config.py
> +import asyncio
не вижу смысла вкладывать сервер конфиг в дополнительную папку, оставь его на уровне server/config.py

2022-10-16 19:16 UTC, kovtunovprog commented on utils/protocol/server.py
> +        request = Request(data[0], data[1], data[2], data[3], data[4], data[5], data[6])
*data

2022-10-17 15:52 UTC, dpirohov commented on utils/protocol/server.py
> +    def __init__(self, host, port, decode_format):
done

2022-10-17 15:53 UTC, dpirohov commented on utils/protocol/server.py
> +        self.HOST = host
done

2022-10-17 15:53 UTC, dpirohov commented on utils/protocol/server.py
> +        self.command_map = {}
done

2022-10-17 15:54 UTC, dpirohov commented on utils/protocol/server.py
> +        server = await asyncio.start_server(self.handle_connection, self.HOST, self.PORT)
Добавил логинг, пока что без конфига, по мере наполнения могу заняться логером, напишу конфиг под него

2022-10-17 15:54 UTC, dpirohov commented on utils/protocol/server.py
> +            print(data)  # TODO: log this or delete after testing
Добавил логинг, пока что без конфига, по мере наполнения могу заняться логером, напишу конфиг под него

2022-10-17 15:56 UTC, dpirohov commented on utils/protocol/server.py
> +    def __init__(self, host, port, decode_format):
done

2022-10-17 15:56 UTC, dpirohov commented on utils/protocol/server.py
> +        print(request)  # TODO: log this or delete after testing
передал в логер

2022-10-17 15:59 UTC, dpirohov commented on utils/protocol/timestamp.py
> +def form_timestamp():
Мы с Ромой подумали что на клиенте будет отображаться системное время сервера, поэтому в протокол добавили метку.

2022-10-17 16:07 UTC, dpirohov commented on utils/protocol/server.py
> +    def decode_protocol(self, data: str) -> Request:
Пока сделал рефактор названия, в принципе протокол одинаковый как с сервера клиенту так и наоборот, функция может быть общей, согласен. я только не понимаю в какую папку пока что закинем

2022-10-17 16:11 UTC, dpirohov commented on utils/protocol/request.py
> +    def form_protocol(self):
так там не FROM а FORM - сформировать

2022-10-17 16:19 UTC, dpirohov commented on utils/protocol/connection.py
> +    def send(self, message: Request):
done

2022-10-17 16:19 UTC, dpirohov commented on utils/protocol/connection.py
> +    token: str
done

2022-10-17 16:21 UTC, dpirohov commented on server/config/config.py
> +import asyncio
refactored

2022-10-17 16:21 UTC, dpirohov commented on utils/protocol/server.py
> +        request = Request(data[0], data[1], data[2], data[3], data[4], data[5], data[6])
гениально :)

2022-10-17 17:29 UTC, dpirohov commented on utils/protocol/request.py
> +class Request:
done

2022-10-17 17:29 UTC, dpirohov commented on utils/protocol/timestamp.py
> +def form_timestamp():
или надо отдельная папка под такие утил функции?

2022-10-17 18:46 UTC, kovtunovprog commented on utils/protocol/server.py
> +            print(data)  # TODO: log this or delete after testing
ок

2022-10-18 10:23 UTC, ArturYastrebov commented on utils/protocol/__init__.py
> +from utils.protocol.timestamp import form_timestamp
не знайшов файл utils.protocol.timestamp в папці

2022-10-18 10:32 UTC, ArturYastrebov commented on utils/protocol/server.py
> +    DATA_CODING_FORMAT = "utf-8"
Можливо є сенс додати  DATA_CODING_FORMAT = "utf-8" в файл server/config.py.
Як на мене тип формату кодування відноситься до налаштування сервера.

2022-10-19 15:18 UTC, dpirohov commented on utils/protocol/server.py
> +    DATA_CODING_FORMAT = "utf-8"
done

2022-10-19 15:18 UTC, dpirohov commented on server/main.py
> +logger = logging.getLogger(__name__)
done

2022-10-19 15:18 UTC, dpirohov commented on server/routes/sign_up.py
> +@server.add_handler('01')
done

2022-10-19 15:18 UTC, dpirohov commented on server/routes/sign_in.py
> +async def sign_in(request: Message):
done

2022-10-19 15:18 UTC, dpirohov commented on utils/protocol/message.py
> +    time: str
done

2022-10-19 15:18 UTC, dpirohov commented on utils/protocol/message.py
> +    status_code: str
done

2022-10-19 15:19 UTC, dpirohov commented on utils/protocol/data_converters.py
> +def form_timestamp():
deleted

2022-10-19 16:53 UTC, kovtunovprog requested changes

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +            await self.command_handler_map.get(message.command)(message)
в хендлер нужно передавать Connection
`await self.command_handler_map.get(message.command)(connection, message)`

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +        self.command_handler_map = {}
Я думаю 
```
command_handler_map
```
можна зробити приватним

__command_handler_map 

а sessions давай поки що видалимо (додамо в наступній задачі)

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +        logger.info(f'Command handle map is formed: {self.command_handler_map}')
цей лог зайвий

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +            await self.command_handler_map.get(message.command)(message)
також треба зробити протектед функцію 
_get_handler(command): self.__command_handler_map.get(message.command)

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +    async def handle_connection(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
цей також треба зробити протектед `_handle_connection`

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +            logger.info(f'Handler collector has started, new handler found: {func.__name__}')
Цей лог зайвий

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +    def add_handler(self, method: str):
давай перейменуємо в `message_handler`

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +        def inner(func):
давай переназвемо `decorator`

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +            logger.debug(f'Received from {writer.get_extra_info("peername")} data: {data}')
f'IN: {writer.get_extra_info("peername")} data: {data}'

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/connection.py
> +        logger.debug(f'Sending to {self.writer.get_extra_info("peername")} data:{message.form_protocol()}')
f'OUT: {self.writer.get_extra_info("peername")} data:{message.form_protocol()}

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/message.py
> +    def form_protocol(self):
Наче я казав що треба `to_procotol`

2022-10-19 16:53 UTC, kovtunovprog commented on server/routes/sign_up.py
> +async def sign_up(request: Message):
тут треба додати connection

2022-10-19 16:53 UTC, kovtunovprog commented on server/routes/sign_in.py
> +async def sign_in(request: Message):
тут також треба додати connection

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +import asyncio
а где вообще использование black?
![image](https://user-images.githubusercontent.com/56452945/196755036-cd6461a2-52d5-496b-8be3-7d4f7ef98b6d.png)

2022-10-19 16:53 UTC, kovtunovprog commented on utils/protocol/server.py
> +import asyncio
все файлы нужно пройти блеком

2022-10-19 17:15 UTC, dpirohov commented on utils/protocol/server.py
> +            await self.command_handler_map.get(message.command)(message)
done

2022-10-19 17:16 UTC, dpirohov commented on utils/protocol/server.py
> +        self.command_handler_map = {}
done

2022-10-19 17:16 UTC, dpirohov commented on utils/protocol/server.py
> +    async def handle_connection(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
done

2022-10-19 17:16 UTC, dpirohov commented on utils/protocol/server.py
> +            logger.info(f'Handler collector has started, new handler found: {func.__name__}')
done

2022-10-19 17:16 UTC, dpirohov commented on utils/protocol/server.py
> +        def inner(func):
done

2022-10-19 17:17 UTC, dpirohov commented on utils/protocol/server.py
> +            logger.debug(f'Received from {writer.get_extra_info("peername")} data: {data}')
done

2022-10-19 17:17 UTC, dpirohov commented on utils/protocol/connection.py
> +        logger.debug(f'Sending to {self.writer.get_extra_info("peername")} data:{message.form_protocol()}')
done

2022-10-19 17:22 UTC, dpirohov commented on server/routes/sign_in.py
> +async def sign_in(request: Message):
done

2022-10-19 22:52 UTC, kovtunovprog requested changes

2022-10-19 22:52 UTC, kovtunovprog commented on utils/protocol/waiter.py
> +    async def wait_message(self):
Тут аннотация нужна на возврат данных

2022-10-19 22:52 UTC, kovtunovprog commented on utils/protocol/server.py
> +        while True:
Вроде и без while работает

2022-10-19 22:52 UTC, kovtunovprog commented on utils/protocol/message.py
> +    def form_protocol(self):
Аннотация на возврат

2022-10-19 22:52 UTC, kovtunovprog commented on utils/protocol/data_converters.py
> +    return request
1. Смысла в том чтобы объявить переменную, а потом ее вернуть нет, можно сразу ее вернуть.
2. Почему бы не добавить это в класс Message?

2022-10-19 22:52 UTC, kovtunovprog commented on utils/protocol/connection.py
> +class Connection:
А в ініт це все додано?

2022-10-19 22:52 UTC, kovtunovprog commented on server/config.py
> +from utils.protocol.server import Server
Оце імпортується напряму, а хотілось би чисто з пакету протокол

2022-10-20 08:24 UTC, dpirohov commented on utils/protocol/waiter.py
> +    async def wait_message(self):
done

2022-10-20 08:25 UTC, dpirohov commented on utils/protocol/message.py
> +    def form_protocol(self):
done

2022-10-20 10:51 UTC, dpirohov commented on utils/protocol/data_converters.py
> +    return request
Перенес этот метод в месседж, файл  data_converters удален по ненадобности

2022-10-20 10:54 UTC, dpirohov commented on server/config.py
> +from utils.protocol.server import Server
не понимаю что надо сделать, заполнить инит пакета протокол? или фул импорт протокол делать?

2022-10-20 10:55 UTC, dpirohov commented on utils/protocol/connection.py
> +class Connection:
Если ты про инит пакета протокол то он пустой, не понимаю что туда добавить надо

2022-10-20 16:07 UTC, kovtunovprog approved these changes
That's good

2022-10-20 18:30 UTC, ArturYastrebov approved these changes

2022-10-20 19:39 UTC, merged