Join to chat handler
kovtunovprog/python_async_chat pull request #20
Opened 2022-11-07 07:13 UTC by KateSamus

2022-11-07 11:19 UTC, dpirohov commented on server/routes/join_to_chat.py
> +    chat_name, user_id, permission = map(
Я думаю что по аналогии с юзером лучше работать с чат id?

2022-11-07 11:21 UTC, dpirohov commented on server/routes/join_to_chat.py
> +                        "response": "YOU WAS JOINED TO CHAT SUCCESSFULLY",
you joined the chat

2022-11-07 11:22 UTC, dpirohov commented on server/routes/join_to_chat.py
> +            chat_member = ChatMember(
Я не знаю нужно ли проверить может такой юзер мембер уже есть? Что будет если мы попытаемся добавить запись которая есть в ДБ

2022-11-07 14:14 UTC, KateSamus commented on server/routes/join_to_chat.py
> +    chat_name, user_id, permission = map(
Згодна
done

2022-11-07 14:14 UTC, KateSamus commented on server/routes/join_to_chat.py
> +            chat_member = ChatMember(
Так, гарна ідея, не подумала про це
done

2022-11-08 11:18 UTC, dpirohov commented on server/routes/join_to_chat.py
> +        chat = await session.scalar(select(Chat).where(Chat.chat_id == chat_id))
немає атрибуту Chat.chat_id є Chat.id

2022-11-08 11:21 UTC, dpirohov commented on server/routes/join_to_chat.py
> +                            "chat_name": chat.name,
AttributeError: 'Chat' object has no attribute 'name'
Chat.chat_name

2022-11-08 11:25 UTC, dpirohov requested changes
Если поправить синтаксис с классом Chat работает, но у нас у чата еще есть тип чата - приватный и группа. Надо это использовать. Если запрос по ИД идет в личный чат в котором он не состоит надо отказывать

2022-11-08 20:07 UTC, KateSamus commented on server/routes/join_to_chat.py
> +        chat = await session.scalar(select(Chat).where(Chat.chat_id == chat_id))
done

2022-11-08 20:07 UTC, KateSamus commented on server/routes/join_to_chat.py
> +                            "chat_name": chat.name,
done

2022-11-08 22:33 UTC, ArturYastrebov requested changes

2022-11-08 22:33 UTC, ArturYastrebov commented on server/routes/join_to_chat.py
> +    logger.info(f"Attempt to join to chat from {user_id}, {chat_id}")
Виводить так:
2022-11-08 23:50:12,120 - utils.logger - INFO - Attempt to join to chat from 5, 2
Можливо так буде інформативніше:
Attempt to join user_id: {user_id} to chat_id: {chat_id}.

2022-11-08 22:33 UTC, ArturYastrebov commented on server/routes/join_to_chat.py
> +                    f"User was added to chat: <{user_id}> - <{chat_id}>, "
Можливо так буде інформативніше.
User_id = {user_id} was added to chat_id: {chat_id}

2022-11-08 22:33 UTC, ArturYastrebov commented on server/routes/join_to_chat.py
> +                    user_id=user_id, chat_id=chat_id, permissions=permission
можливо поставити permission = 0 за завмовчуванням для нових юзерів. І це буде означати що при додаванні в групу, юзер буде мати звичайні права юзера за завмовчуванням. а права адміна йому вже буде призначати власник групи чи інший адмін?

2022-11-08 22:33 UTC, ArturYastrebov commented on server/routes/join_to_chat.py
> +            result = await session.scalar(select(ChatMember).where(ChatMember.user_id == user_id))
Тут потрібна подвійна умова, оскільки юзер може бути в іншому чаті. 
ChatMember.user_id == user_id and ChatMember.chat_id == chat_id

2022-11-08 22:33 UTC, ArturYastrebov commented on server/routes/join_to_chat.py
> +            result = await session.scalar(select(ChatMember).where(ChatMember.user_id == user_id))
Змінна result не інформативна... можливо замінити на member_in_chat?

2022-11-09 20:46 UTC, KateSamus commented on server/routes/join_to_chat.py
> +            result = await session.scalar(select(ChatMember).where(ChatMember.user_id == user_id))
done on both

2022-11-09 20:46 UTC, KateSamus commented on server/routes/join_to_chat.py
> +                    f"User was added to chat: <{user_id}> - <{chat_id}>, "
done

2022-11-09 20:47 UTC, KateSamus commented on server/routes/join_to_chat.py
> +    logger.info(f"Attempt to join to chat from {user_id}, {chat_id}")
done

2022-11-10 09:52 UTC, ArturYastrebov requested changes

2022-11-10 09:56 UTC, KateSamus commented on server/routes/join_to_group_chat.py
> +                    "join_to_chat",
так, дякую
done

2022-11-11 16:58 UTC, dpirohov approved these changes
супер

2022-11-11 18:03 UTC, ArturYastrebov approved these changes
Nice job!

2022-11-11 18:51 UTC, merged