created func get_all_groups
kovtunovprog/python_async_chat pull request #22
Opened 2022-11-09 20:54 UTC by ArturYastrebov

2022-11-09 21:13 UTC, KateSamus commented on server/routes/get_all_groups.py
> +            chats = await session.scalars(select(Chat).where(Chat.type == 1))
Яка різниця між 13 і 23 строкою?

2022-11-09 21:57 UTC, KateSamus approved these changes

2022-11-10 08:53 UTC, dpirohov commented on server/routes/get_all_groups.py
> +    logger.info(f"Attempt to get all groups")
from who?

2022-11-10 08:54 UTC, dpirohov commented on server/routes/get_all_groups.py
> +            chats = [{"chat_name": chat.chat_name, "id": chat.id} for chat in chats]
"chat_id": chat.id

2022-11-10 08:56 UTC, dpirohov commented on server/routes/get_all_groups.py
> +    logger.info(f"Attempt to get all groups")
в логе бы видеть не просто на каком моменте крашнулось а кто его крашнул в случае чего

2022-11-10 09:34 UTC, ArturYastrebov commented on server/routes/get_all_groups.py
> +    logger.info(f"Attempt to get all groups")
++

2022-11-10 09:34 UTC, ArturYastrebov commented on server/routes/get_all_groups.py
> +            chats = [{"chat_name": chat.chat_name, "id": chat.id} for chat in chats]
++

2022-11-11 17:47 UTC, dpirohov commented on server/routes/get_all_groups.py
> +        return await connection.send_message(response)
перекинь влево что б закрыть сессию до ретерна

2022-11-11 17:47 UTC, dpirohov commented on server/routes/get_all_groups.py
> +async def get_group_members(message: Message, connection: Connection):
![image](https://user-images.githubusercontent.com/94925700/201399201-f16fcd2d-48d3-4e66-b093-492a017c94a4.png)

2022-11-11 17:48 UTC, dpirohov requested changes
надо переделать на 1 запрос в бд

2022-11-11 17:50 UTC, dpirohov commented on server/routes/get_all_groups.py
> +        return await connection.send_message(response)
или весь иф можно сдвинуть сразу после ответа от дб

2022-11-11 17:55 UTC, ArturYastrebov commented on server/routes/get_all_groups.py
> +async def get_group_members(message: Message, connection: Connection):
++ Done

2022-11-11 17:56 UTC, ArturYastrebov commented on server/routes/get_all_groups.py
> +        return await connection.send_message(response)
+ done!

2022-11-11 18:05 UTC, dpirohov approved these changes
++

2022-11-11 18:07 UTC, merged