Leave_chat
kovtunovprog/python_async_chat pull request #24
Opened 2022-11-11 11:34 UTC by Alaru-dev

added method leave_chat to client/client
added module leave_chat to server/routes
updated init at server/routes

2022-11-11 17:06 UTC, KateSamus commented on server/routes/leave_chat.py
> +    chat_id, user_id = content["chat_id"], content["user_id"]
краще зробити через content.get("chat_id") etc, якщо з якоїсь причини не прийдуть дані

2022-11-11 17:08 UTC, KateSamus commented on server/routes/leave_chat.py
> +                user_row = await session.scalar(
можна просто user

2022-11-11 17:10 UTC, KateSamus commented on server/routes/leave_chat.py
> +                    response = Message(
А де ти юзера з ДБ видаляєш?

2022-11-11 17:12 UTC, KateSamus commented on server/routes/leave_chat.py
> +                    Message.decode_content_to_json(
А чого юзер не може вийти з приватного чату?

2022-11-11 17:14 UTC, Alaru-dev commented on server/routes/leave_chat.py
> +                    response = Message(
2й рядок від комента вище, delete

2022-11-11 17:17 UTC, Alaru-dev commented on server/routes/leave_chat.py
> +                    Message.decode_content_to_json(
на мій погляд якось не логічно якщо зможе надо обговорити

2022-11-12 08:42 UTC, dpirohov commented on server/routes/leave_chat.py
> +        chat_type = await session.scalar(select(Chat.type).where(Chat.id == chat_id))
Я б не проверял чат тайп

2022-11-12 13:46 UTC, dpirohov commented on server/routes/leave_chat.py
> +                            {"response": "CHAT WAS LEAVED", "chat_id": chat_id}
YOU LEFT CHAT

2022-11-12 13:47 UTC, dpirohov commented on server/routes/leave_chat.py
> +                Message.decode_content_to_json({"response": "CHAT DAS NOT EXIST"}),
Такого не будет, если нет чата значит нет и чат мембера

2022-11-12 13:48 UTC, dpirohov commented on server/routes/leave_chat.py
> +                        {"response": "YOU CAN`T LEAVE PRIVATE CHAT"}
Пока убираем

2022-11-12 13:51 UTC, dpirohov commented
1. Сразу делит чатмембера и в зависимости от ответа давать респонс
2. Сделать запрос на чат мембера, проанадизировать и удалить в случае нужды

2022-11-12 13:53 UTC, dpirohov requested changes
1. Сразу делит чатмембера и в зависимости от ответа давать респонс
2. Сделать запрос на чат мембера, проанадизировать и удалить в случае нужды

2022-11-13 15:24 UTC, closed without merging

2022-11-13 15:27 UTC, Alaru-dev commented
merged into too many branches