Add private chat creation to create chat
kovtunovprog/python_async_chat pull request #28
Opened 2022-11-13 17:14 UTC by KateSamus

2022-11-14 14:47 UTC, Alaru-dev requested changes

2022-11-14 14:47 UTC, Alaru-dev commented on server/routes/create_chat.py
>                  Protocol.SERVER.value,
-  має сенс створювати в if-else не повністю респонс, а тількі респонс-контент, а вже перед сендом додавати респонс, буде менше рядків

2022-11-14 14:47 UTC, Alaru-dev commented on server/routes/create_chat.py
> +                chat = Chat(chat_name=chat_name, creator_id=creator_id, type=chat_type)
-  коли створюємо приватний чат, ми самі створюємо ім'я цього чату або воно повинно формуваться з нікнеймів мемберів на десктопі, чи всередині клієнта?

2022-11-14 17:28 UTC, KateSamus commented on server/routes/create_chat.py
> +                chat = Chat(chat_name=chat_name, creator_id=creator_id, type=chat_type)
Ім'я приватного чату формуватиметься на десктопі автоматично. Наприкад, nickname1 - nickname2

2022-11-14 17:31 UTC, KateSamus commented on server/routes/create_chat.py
>                  Protocol.SERVER.value,
Згодна

2022-11-14 18:36 UTC, Alaru-dev approved these changes

2022-11-15 13:24 UTC, dpirohov commented on server/routes/create_chat.py
> +            if chat_type == 0:
В глобал енаме есть чат тайп, надо использовать его + читая код будет понятно что значит условие

2022-11-15 13:35 UTC, dpirohov commented on server/routes/create_chat.py
> +                if chat_type == 0:
Условие дублируется с 25 строкой, может надо обьединить?

2022-11-15 14:04 UTC, dpirohov commented on server/routes/create_chat.py
>      return await connection.send_message(response)
Не совсем понимаю как второй юзер должен узнать что создался приватный чат? Должно ли ему приходить уведомление сразу что б клиент у себя записал хотя бы чат ид и чат нейм, а после того как туда прилетит месседж откроет это окно. 
Если получатель оффлайн то пишем в дб все получается, при логине клиент шлет запросы на апдейты и получает их. Тут уведомление второго никак не реализовано

2022-11-15 15:03 UTC, Alaru-dev commented on server/routes/create_chat.py
>      return await connection.send_message(response)
Дім це буде окремий таск, що юзер коли заходить, десктоп отримує перелік всіх чатів де він чатмембер та створює під них вікна або кнопочки, або якщо він онлайн(а хтось створив приватний чат в цей час), коли він отримає перше повідомлення то вже тоді створюється приватний чат на десктопі та туди приходить повідомлення.

2022-11-15 18:38 UTC, dpirohov commented on server/routes/create_chat.py
>      return await connection.send_message(response)
согласен

2022-11-15 18:39 UTC, dpirohov commented on server/routes/create_chat.py
> +        response_content = {"response": CreateChat.RESPONSE_SECOND_USER_SPECIFIED.value}
нам нет смысла это проверять и это респонсить. мы через гет все равно получим None если єтот ид нам передали, запросим юзера с таким ИД и тоже получим None и просто дадим ответ что нет такого юзера

2022-11-15 18:59 UTC, dpirohov requested changes
Код вроде работает но как по мне он тяжело читаем, у нас тут очень много ифов елсов.
Используя полностью твой код я попробовал в 3 ифа переделать. Посмотри, сама реши что делать
![image](https://user-images.githubusercontent.com/94925700/202002563-122657a8-9eb8-4336-a4a7-ce1c83b9ad20.png)
![image](https://user-images.githubusercontent.com/94925700/202002586-7cc34822-0dde-404d-bd2c-036df5cb2a1c.png)

2022-11-16 11:59 UTC, KateSamus commented on server/routes/create_chat.py
>      return await connection.send_message(response)
Ромі у відповідь
Перевірка на це відбувається, коли перевіряється чатнейм. Десктоп сам формує чатнейм для приватного чату, умовно nickname1 - nickname2, тому якщо такий чатнейм вже є, це означає що приватний чат вже створено

2022-11-16 14:05 UTC, ArturYastrebov approved these changes
Агонь!

2022-11-16 14:14 UTC, dpirohov approved these changes

2022-11-16 15:05 UTC, merged