Sq lite database
kovtunovprog/python_async_chat pull request #3
Opened 2022-10-17 16:44 UTC by ArturYastrebov

file config.py - create connection between the database and the program using a package SQLAlchemy.
file user.py - create table Users
file db.py - create async_session, create async func:
       - async func async_clear_all - refresh table DB (clear and create table DB)
       - async func async_add - add data to table DB
       - async func async_select - get data from DB

2022-10-17 19:23 UTC, kovtunovprog commented
Файл базы данных нужно удалить и добавить в .gitignore

2022-10-17 19:23 UTC, kovtunovprog requested changes

2022-10-18 09:12 UTC, ArturYastrebov commented on server/server_utils/db.py
> +# async def async_select():
+

2022-10-18 09:12 UTC, ArturYastrebov commented on server/server_utils/db.py
> +async def async_clear_all():
+ 
функція видаляє та створює всі таблички, клас яких при наслідувався від класу Base.

2022-10-18 09:17 UTC, ArturYastrebov commented on server/server_utils/db.py
> +async def async_select():
Базова функція для перевірки функціоналу ДБ. Буду змінювати під потреба запитів від сервера та клієнта.

2022-10-18 09:17 UTC, ArturYastrebov commented on server/server_utils/db.py
> +            print(row.nickname, row.password, row.email)
+

2022-10-18 09:18 UTC, ArturYastrebov commented on server/server_utils/db.py
> +asyncio.run(async_clear_all())
+

2022-10-18 09:19 UTC, ArturYastrebov commented on server/server_utils/db.py
> +from arhiv.PycharmProjects.pythonProject.homework.artur_yastrebov.sqlalchemy_asyncio.server.config import engine
++

2022-10-18 09:28 UTC, ArturYastrebov commented on server/models/user.py
> +    __tablename__ = "Users"
++

2022-10-18 17:47 UTC, kovtunovprog requested changes

2022-10-18 17:47 UTC, kovtunovprog commented on server/server_utils/db.py
> +async def select_data_from_table(tablename: Base):
Це треба прибрати

2022-10-18 17:47 UTC, kovtunovprog commented on server/server_utils/db.py
> +async def create_user(nickname: str, password: str, email: str = None):
це також некорисна фукнція

2022-10-18 17:47 UTC, kovtunovprog commented on server/server_utils/db.py
> +async def main():
це також тут не треба

2022-10-18 17:47 UTC, kovtunovprog commented on server/server_utils/db.py
> +if __name__ == '__main__':
і це

2022-10-18 17:47 UTC, kovtunovprog commented on server/server_utils/db.py
> +import asyncio
файл думаю можна перейменувати db_utils.py

2022-10-18 17:47 UTC, kovtunovprog commented on .gitignore
> +#.idea/
Треба видалити з репозиторія database.db 
Це конкретна база даних, яка не має відношення до реального серверу
Та додати сюди.

2022-10-18 17:47 UTC, kovtunovprog commented on .gitignore
> +#.idea/
*.db (тільки треба видалити самому бо воно само по собі не видалиться)

2022-10-19 11:57 UTC, ArturYastrebov commented on .gitignore
> +#.idea/
++

2022-10-19 19:16 UTC, kovtunovprog approved these changes

2022-10-20 22:30 UTC, dpirohov approved these changes

2022-10-22 09:30 UTC, merged