Desktop (PyQt base)
kovtunovprog/python_async_chat pull request #6
Opened 2022-10-17 19:34 UTC by KateSamus

- Start Window of Chat
- Sign Up and Sign In Windows of Chat
- !Chat opens from start_window

start_window, sign_up_window, sign_in_window to check
chat_window is in progress

2022-10-18 16:50 UTC, kovtunovprog commented
Вкладати в додатковий пакет кожне вікно не потрібно

windows/
auth/
- sign_up.py
- sign_in.py
main_window.py

2022-10-18 16:52 UTC, kovtunovprog commented
`
class BaseWindow:
def __init__(self, client: AsyncClient):
...

2022-10-18 17:13 UTC, kovtunovprog requested changes

2022-10-18 17:13 UTC, kovtunovprog commented on desktop/windows/start_window/start_window.py
> +        self.window = QtWidgets.QMainWindow()
тоді можна буде не робити 4 виклики, а ініціалізувати UiSignUpMenu(self.client)

2022-10-18 17:13 UTC, kovtunovprog commented on desktop/windows/start_window/start_window.py
> +class Ui_AsynchronousChat(QMainWindow):
Можливо нам не треба спадкуватися від QMainWindow, бо ми його все одно передаємо сюди і використовуємо переданий об'єкт.

2022-10-18 17:13 UTC, kovtunovprog commented on desktop/windows/start_window/start_window.py
> +    def setupUi(self, AsynchronousChat):
Треба всі методи де можливо переписати за python конвенцією for example setup_ui

Всюди треба додати аннотації (type hints)

2022-10-18 17:13 UTC, kovtunovprog commented on desktop/windows/chat_window.py
> +from PyQt5 import QtCore, QtGui, QtWidgets
Не може бути двох імплементацій. @PQBob ми далі йдемо з кодовою базою інших файлів.

2022-10-19 15:45 UTC, KateSamus commented on desktop/windows/start_window/start_window.py
> +class Ui_AsynchronousChat(QMainWindow):
done

2022-10-19 15:45 UTC, KateSamus commented on desktop/windows/start_window/start_window.py
> +def main():
done

2022-10-19 15:45 UTC, KateSamus commented on desktop/windows/start_window/start_window.py
> +        self.window = QtWidgets.QMainWindow()
done

2022-10-19 15:45 UTC, KateSamus commented on desktop/windows/start_window/start_window.py
> +class Ui_AsynchronousChat(QMainWindow):
done

2022-10-19 15:45 UTC, KateSamus commented on desktop/windows/chat_window.py
> +from PyQt5 import QtCore, QtGui, QtWidgets
done

2022-10-19 23:23 UTC, kovtunovprog requested changes
Стало значно-значно краще, є мілкі нюанси.

2022-10-19 23:23 UTC, kovtunovprog commented on desktop/windows/base.py
> +class BaseWindow(QMainWindow):
А можна так зробити щоб воно не спадкувалося в принципі від нього, а просто приймало при ініціалізації?

2022-10-19 23:23 UTC, kovtunovprog commented on desktop/__init__.py
> +from desktop.windows.start_window import StartWindow
Це обов'язково?

2022-10-19 23:23 UTC, kovtunovprog commented on desktop/main.py
> +    if __name__ == "__main__":
Оце має бути в самому файлі

2022-10-19 23:23 UTC, kovtunovprog commented on desktop/windows/__init__.py
> +from desktop.windows.base import BaseWindow
Якщо без цього працює не бачу в цьому сенсу

2022-10-19 23:23 UTC, kovtunovprog commented on desktop/windows/base.py
> +    def __init__(self, client):
Типу щоб приймати window в ініті. Так ми трошки сепаруємо наш код від pyqt

2022-10-19 23:23 UTC, kovtunovprog commented on desktop/windows/auth/sign_up_window.py
> +    def __init__(self, client):
Це вже в базовому класі є, тут не треба

2022-10-19 23:23 UTC, kovtunovprog commented on desktop/windows/auth/sign_in_window.py
> +    def return_to_start_menu(self):
Це є в двох сторінках вже і буде ще після вилогіну, треба цей метод кудись винести. Наприклад в міксін.

2022-10-19 23:23 UTC, kovtunovprog commented on desktop/windows/auth/sign_in_window.py
> +    def __init__(self, client):
Це вже в базовому є

2022-10-19 23:23 UTC, kovtunovprog commented on desktop/main.py
> +        app = QtWidgets.QApplication(sys.argv)
Схоже цей апп використовується тільки для виходу. В старт вікно має це вміти.

2022-10-19 23:23 UTC, kovtunovprog commented on desktop/main.py
> +        sys.exit(app.exec_())
```suggestion
        sys.exit(window.exec_())
```

2022-10-21 14:47 UTC, KateSamus commented on desktop/main.py
> +        sys.exit(app.exec_())
свариться, залишила

2022-10-21 14:47 UTC, KateSamus commented on desktop/main.py
> +        app = QtWidgets.QApplication(sys.argv)
просить спочатку QApplication ініціалізувати, залишила

2022-10-21 14:47 UTC, KateSamus commented on desktop/windows/auth/sign_in_window.py
> +    def __init__(self, client):
done

2022-10-21 14:47 UTC, KateSamus commented on desktop/windows/auth/sign_in_window.py
> +    def return_to_start_menu(self):
створила mixins, але мені здається що трохи криво...

2022-10-21 14:47 UTC, KateSamus commented on desktop/windows/auth/sign_up_window.py
> +    def __init__(self, client):
done

2022-10-21 14:48 UTC, KateSamus commented on desktop/windows/base.py
> +    def __init__(self, client):
done ↑

2022-10-21 14:48 UTC, KateSamus commented on desktop/windows/__init__.py
> +from desktop.windows.base import BaseWindow
без цього не хоче його імпортувати, залишила

2022-10-21 14:48 UTC, KateSamus commented on desktop/main.py
> +    if __name__ == "__main__":
done

2022-10-21 14:48 UTC, KateSamus commented on desktop/windows/base.py
> +class BaseWindow(QMainWindow):
додала метод який створює інстанс QMainWindow

2022-10-21 18:13 UTC, kovtunovprog commented on desktop/windows/auth/sign_up_window.py
> +        self.window = self.create_window()
в кожному вікні робиться ця дія

принцип dry нам каже don't repeat yourself
Тобто якщо щось робиться, воно має робитися в одному місці

2022-10-21 20:02 UTC, dpirohov commented on desktop/windows/auth/sign_in_window.py
> +        sign_in_info = f"{nickname.text()};;{password.text()}"
Протокол выглядит так: command;;sender;;receiver;;toke;;content

2022-10-21 20:03 UTC, dpirohov commented on desktop/windows/auth/sign_in_window.py
> +    def read_sign_in_info(self, nickname: QLineEdit, password: QLineEdit):
не хватает type hintа что функция вернет

2022-10-21 20:07 UTC, dpirohov commented on desktop/windows/auth/sign_in_window.py
> +        sign_in_info = f"{nickname.text()};;{password.text()}"
И у нас есть dataclass Message который будет находится в клиенте, мы уже можем сформировать обьект класса месседж после считывания, который отправим методом send_message(self, message: Message) из клиента

2022-10-21 20:09 UTC, dpirohov commented on desktop/windows/auth/sign_up_window.py
> +        return sign_up_info
Тайп хинт что возвратит
Протокол выглядит так: command;;sender;;receiver;;toke;;content
И у нас есть dataclass Message который будет находится в клиенте, мы уже можем сформировать обьект класса месседж после считывания, который отправим методом send_message(self, message: Message) из клиента

2022-10-21 20:10 UTC, dpirohov commented on desktop/windows/auth/sign_up_window.py
> +        sign_up_info = f"{email.text()};;{nickname.text()};;{password.text()};;{confirm_password.text()}"
нам наверное два пароля передавать не надо на сервер, можно тут какую то функцию проверки совпадения пароля сделать, а на сервер отправить один для записи в ДБ

2022-10-21 20:14 UTC, dpirohov commented on desktop/windows/start_window.py
> +from desktop.windows.auth.sign_in_window import SignInWindow
В ините пакета эти импорты прописаны уже, может сам пакет тогда импортировать

2022-10-21 20:16 UTC, dpirohov commented on desktop/main.py
> +    import sys
а его так и надо испортировать сюда? или можно на ряду со всеми импортами? Так как это мейн он в любом случае заимпортится же

2022-10-23 10:08 UTC, KateSamus commented on desktop/windows/auth/sign_up_window.py
> +        self.window = self.create_window()
done, перенесла в BaseWindow

2022-10-23 10:08 UTC, KateSamus commented on desktop/windows/auth/sign_up_window.py
> +        self.window.title = QLabel(self.window)
done, розбила на окремі методи для кожного об'єкта вікна, ініціалізацію вікна та заголовка вдалося перенести в BaseWindow

2022-10-23 10:09 UTC, KateSamus commented on desktop/windows/auth/sign_in_window.py
> +        sign_in_info = f"{nickname.text()};;{password.text()}"
Задача наступній людині, яка буде підв'язувати клієнта до gui, я тільки створюю базові вікна та на майбутнє зчитую з полів

2022-10-23 10:09 UTC, KateSamus commented on desktop/windows/auth/sign_in_window.py
> +    def read_sign_in_info(self, nickname: QLineEdit, password: QLineEdit):
done

2022-10-23 10:10 UTC, KateSamus commented on desktop/windows/auth/sign_up_window.py
> +        return sign_up_info
type hint done
Ініціалізація Message - завдання наступній людині

2022-10-23 10:11 UTC, KateSamus commented on desktop/windows/start_window.py
> +from desktop.windows.auth.sign_in_window import SignInWindow
done, імпортнула все з auth

2022-10-23 10:11 UTC, KateSamus commented on desktop/main.py
> +    import sys
Ні, перенесла на гору

2022-10-23 10:12 UTC, KateSamus commented on desktop/windows/auth/sign_up_window.py
> +        sign_up_info = f"{email.text()};;{nickname.text()};;{password.text()};;{confirm_password.text()}"
Просто зчитую поля на майбутнє, наступна людина буде ініціалізувати Sign Up і всі пов'язані з цим операції

2022-10-24 10:46 UTC, dpirohov commented on desktop/windows/mixins.py
> +        curr_window.close()
А нам надо что б импорт был из функци? я бы переписал по другому, и окна которые мы хотим можно в ините инициализировать, мы ж для этого клас миксин вроде как и сделали

2022-10-24 10:47 UTC, dpirohov commented on desktop/windows/mixins.py
> +        curr_window.close()
![image](https://user-images.githubusercontent.com/94925700/197509152-99b62648-f6ee-4f67-b3c1-b065898a9d1b.png)

2022-10-24 18:35 UTC, kovtunovprog commented on desktop/windows/start_window.py
> +    def setup_start_window(self):
def setup_window покласти в BaseWindow, а тут перевизначити
(можна як абстрактний метод і BaseWindow як абстрактний клас)

2022-10-24 18:38 UTC, kovtunovprog commented on desktop/windows/base.py
> +class BaseWindow:
BaseWindowHandler і по аналогії всі інші класи

2022-10-25 13:09 UTC, KateSamus commented on desktop/windows/start_window.py
> +    def setup_start_window(self):
done

2022-10-25 19:08 UTC, kovtunovprog approved these changes

2022-10-27 11:47 UTC, dpirohov approved these changes

2022-10-28 21:53 UTC, merged