base client v0
kovtunovprog/python_async_chat pull request #7
Opened 2022-10-18 10:04 UTC by Alaru-dev

2022-10-18 15:34 UTC, dpirohov commented on client/client.py
> +
request сменили на message  и глянь там в утилсах создан файл utils/protocol/data_converters.py где будет время и метод parse_protocol_message

2022-10-18 15:35 UTC, dpirohov commented on client/client.py
> +        data = string.split(';;')
utils/protocol/data_converters.py import  parse_protocol_message

2022-10-18 15:36 UTC, dpirohov commented on client/client.py
> +        self.command_map = {}
self.command_handler_map

2022-10-18 15:36 UTC, KateSamus commented on client/client.py
> +        request = Request(data[0], data[1], data[2], data[3], data[4], data[5], data[6])
(*data) для розпакування достатньо

2022-10-18 15:38 UTC, KateSamus commented on client/client.py
> +        print(request)
Print для перевірки реквесту був?

2022-10-18 15:40 UTC, dpirohov commented on client/client.py
> +    def __init__(self, HOST, PORT):
kovtunovprog 2 days ago
думаю можно добавить дефолты для полей
host, port
я думаю что это может быть так host=localhost, port=5000

2022-10-18 15:44 UTC, KateSamus commented on client/client.py
> +        return request.form_protocol()     #add to Request func - form_timestamp
Не розумію, що робить ця функція, бо не бачу оголошення або імпорт функції form_protocol

2022-10-18 15:56 UTC, KateSamus commented on client/client.py
> +            await self.send(writer, request.encode("utf-8"))
Формат кодування - постійна зміна, яка багаторазово використовується в коді, є сенс винести її в глобальний простір, на рівні з портом і хостом. Наприклад:
DATA_CODING_FORMAT = "utf-8"

2022-10-18 16:14 UTC, dpirohov requested changes

2022-10-18 17:41 UTC, kovtunovprog commented
Пройдись black по коду і flake8

2022-10-19 12:34 UTC, kovtunovprog requested changes

2022-10-19 14:43 UTC, Alaru-dev commented on client/client.py
> +
замінів імпорт, тільки Месседж та Коннект

2022-10-19 14:44 UTC, Alaru-dev commented on client/client.py
> +        data = string.split(';;')
removed from class

2022-10-19 14:44 UTC, Alaru-dev commented on client/client.py
> +        self.command_map = {}
removed

2022-10-19 14:48 UTC, Alaru-dev commented on client/client.py
> +        return request.form_protocol()     #add to Request func - form_timestamp
removed

2022-10-19 14:50 UTC, Alaru-dev commented on client/client.py
> +
+

2022-10-19 18:35 UTC, kovtunovprog requested changes

2022-10-19 18:35 UTC, kovtunovprog commented on client/client.py
> +from server.config import HOST, PORT, DATA_CODING_FORMAT
не, такие импорты тут некоректны

2022-10-19 18:35 UTC, kovtunovprog commented on client/client.py
> +    def __init__(self):
дай ему в инит принимать параметры host, port

2022-10-19 18:35 UTC, kovtunovprog commented on client/client.py
> +    def __init__(self):
просто с дефолтами

2022-10-19 18:35 UTC, kovtunovprog commented on client/client.py
> +                raise Exception("Connection closed")
ConnectionError

2022-10-19 18:35 UTC, kovtunovprog commented on client/client.py
> +from server.config import HOST, PORT, DATA_CODING_FORMAT
Эта инфа должна быть в utils/protocol/envs.py
LOCAL = ("localhost", 5050)

2022-10-19 18:35 UTC, kovtunovprog commented on client/client.py
> +    async def listen_incoming(self):
может быть это стоит положить в коннекшн

2022-10-20 16:16 UTC, kovtunovprog requested changes

2022-10-20 16:16 UTC, kovtunovprog commented on client/client.py
> +            print(message)
Логгирование и так есть принт не нужен

2022-10-20 16:16 UTC, kovtunovprog commented on client/client.py
> +    async def send_messages(self, message):
Може send_message? Наче тільки одне повідомлення відправляється.

2022-10-20 16:16 UTC, kovtunovprog commented on client/client.py
> +        await self.connection.send_message_wait_answer(message)
return ...

2022-10-20 16:16 UTC, kovtunovprog commented on client/client.py
> +        write = asyncio.create_task(
Це можна повністю видаляти

2022-10-20 16:16 UTC, kovtunovprog commented on client/client.py
> +class Client:
Давай ще мабуть клієнт перенесемо базовий в протокол, а реалізацію методів вже в папці зробимо

2022-10-20 19:29 UTC, dpirohov commented on utils/protocol/client.py
> +        self.connection = Connection(writer, reader)
Може надо в инит перенести, пайчарму не нравится что оно тут инициализируется. По логике мы же запустили клиент и конекта еще нет, можн в инит добавить self.connection = False/None и т.д.

2022-10-20 19:53 UTC, kovtunovprog commented on utils/protocol/client.py
> +        self.connection = Connection(writer, reader)
Можно добавить в класс

class Client:
  connection: Connection

2022-10-20 19:55 UTC, kovtunovprog approved these changes
That's good

2022-10-20 20:28 UTC, dpirohov approved these changes

2022-10-20 21:27 UTC, merged